### ISSUE TITLE
【Typo】『1-8. 最適なパラメータを求める』の動画の数式が誤っていませんか？（脱ブラックボックスコース）

### ISSUE THREAD

**Issue by nnDropout1** [kikagaku/kikagaku-public-issues#10]
動画の10:23～あたりで映されている以下の数式についてです。
![image](https://user-images.githubusercontent.com/76175412/105612541-3d83f080-5e00-11eb-82b6-e992a42bc276.png)

最下行の左辺に以下の数式があります。
![image](https://user-images.githubusercontent.com/76175412/105612024-6bffcc80-5dfc-11eb-8546-2637aab48189.png)

この式ですが、前後の文脈からすると以下の数式の誤記ではありませんか？
![image](https://user-images.githubusercontent.com/76175412/105612039-7de16f80-5dfc-11eb-987e-07feec0ecb79.png)

損失関数を重みで微分する流れは以下のイメージです。
![image](https://user-images.githubusercontent.com/76175412/105612502-f0078380-5dff-11eb-8f34-8a09754d2f39.png)

私の理解が誤っていましたら申し訳ありません。ご確認をよろしくお願いいたします。

**Comment by kazuki-310** [comment]
脱ブラックコースを受講頂きありがとうございます。

数式の件ご指摘頂き誠にありがとうございます。
こちら修正次第連絡致します。今後ともよろしくお願い致します。
