### ISSUE TITLE
サンプル数の意味について

### ISSUE THREAD

**Issue by todoroki7** [kikagaku/kikagaku-public-issues#11]
脱ブラックボックスコースの数学の基礎1において短回帰分析についての講義でサンプル数を誤って使用しています。
正しくはサンプルサイズではないでしょうか。サンプルサイズが３で。サンプル数は1ではないですか？

**Comment by kazuki-310** [comment]
脱ブラックボックスコースを受講頂きありがとうございます。

> 脱ブラックボックスコースの数学の基礎1において短回帰分析についての講義でサンプル数を誤って使用しています。
正しくはサンプルサイズではないでしょうか。サンプルサイズが３で。サンプル数は1ではないですか？

こちらの質問ですが、英語で number of samples ですので、日本語でサンプル数とあっております。
※ ただし、学術領域（特に信号処理系）によって、デジタルデータの離散値ひとつを１サンプルと呼ぶので、窓幅360サンプルで１サンプルサイズと呼ぶこともあります。

引き続きよろしくお願い致します。
