### ISSUE TITLE
【Typo】『2-3. 主要な演算』誤植

### ISSUE THREAD

**Issue by Zmaj-web** [kikagaku/kikagaku-public-issues#12]
誤植の報告です。
『2-3. 主要な演算』にて、行列のサイズ表記について誤植がありました。

![typo_2-3_the_main_of_operation](https://user-images.githubusercontent.com/78254705/106352628-004fbf00-6328-11eb-9094-4d787145f48e.png)

こちらが修正の差分です。よろしくお願いいたします。

<img src="https://user-images.githubusercontent.com/78254705/106352962-69383680-632a-11eb-8f8c-1a13aa458345.png" width="320px">

**Comment by kazuki-310** [comment]
この度はご指摘頂きありがとうございます。
また、修正点まで頂きありがとうございます。

こちら修正致しました。
引き続きよろしくお願い致します。
