### ISSUE TITLE
数学の基礎(Step2) 重回帰分析のテスト問題について

### ISSUE THREAD

**Issue by ted-17** [kikagaku/kikagaku-public-issues#13]
Q1. 回答が合っているにも関わらず不正解とみなされます。
![image](https://user-images.githubusercontent.com/66860222/106475805-b6aed200-64e9-11eb-8a03-946b1717d7f7.png)

Q2. そもそも問題として成り立っておりません。
![image](https://user-images.githubusercontent.com/66860222/106475857-c62e1b00-64e9-11eb-8d06-1e61d0a55d28.png)

**Comment by keisuke0617** [comment]
Q2 の答えが-7　みたいなのですが、なぜですか？？

**Comment by kazuki-310** [comment]
脱ブラックボックス受講頂きありがとうございます！
ご指摘頂きありがとうございます。こちら問題文に誤りがありました。

編集次第また連絡致します。
