### ISSUE TITLE
キカガク(脱ブラックボックスコース) 数学の基礎part1 合成関数の微分 テストQ3 の解説のお願いについて

### ISSUE THREAD

**Issue by harasyoyotaro** [kikagaku/kikagaku-public-issues#15]
https://www.kikagaku.ai/course/blackbox/learn/math-basic1/differentiation-of-composite-function
こちらのページのQ3の問題を何度解いても、正解にならず、

大変申し訳ない気持ちでいっぱいですが、
解説をお願いできたらと思いお問い合わせさせてもらいました。

ご検討いただけたら幸いです。
何卒宜しくお願い致します。

**Comment by kikagaku** [comment]
ご質問いただき、ありがとうございます。
テストに関する内容ですのでコメントは控えますがご了承ください。
解けない時にも次に進んでみるとヒントがあったり、思いついたりするものですので、諦めずに進めてみてください。応援しています。
