### ISSUE TITLE
4-4 Q3予測値の値が間違いではないかと思われます。

### ISSUE THREAD

**Issue by kzkamitani** [kikagaku/kikagaku-public-issues#16]
ｙ3が0.2,0,0.8で与えられていますが、
pythonでln0はｰinfと出力され、交差エントロピーの出力はエラーメッセージがでます。
RuntimeWarning: divide by zero encountered in log・・・

0の部分が誤りではと想像しているのですがいかがでしょうか。

**Comment by kazuki-310** [comment]
ご質問頂きありがとうございます。
こちら確認次第再度ご連絡させて頂きます。

引き続きよろしくお願い致します。

**Comment by kazuki-310** [comment]
@kzkamitani 
こちら確認いたしましたところ、用意されている答えに間違えはありません。
しかし、予測確率をすべて使用すると 0 の部分でエラーが起きてしまいます。
正解クラスに対応する予測値のみを使って計算していただければと思います。

また、参考として、下記のリンクをお送りしますので、計算の際に活用して頂けたらと思います。
http://wild-data-chase.com/index.php/2018/12/23/post-270/
引き続きよろしくお願いいたします。
