### ISSUE TITLE
【質問】2.7ベクトル関連の関数のテストについて　(脱ブラックボックスコース)

### ISSUE THREAD

**Issue by i-tosh** [kikagaku/kikagaku-public-issues#17]
テストの中で
_y=max(0,u)_
という関数が唐突に出てきますが、この関数の定義は何でしょうか?
テストの中で記載して貰えるとありがたいです。

**Comment by kazuki-310** [comment]
ご質問頂きありがとうございます！

> y=max(0,u)
という関数が唐突に出てきますが、この関数の定義は何でしょうか?

こちらに関しては、下記の章で詳しく説明してますので参考にして頂けたらなと思います。
https://www.kikagaku.ai/course/blackbox/learn/nn-math/fp-nonlinear-transformation/

引き続きよろしくお願い致します。

**Comment by i-tosh** [comment]
河原様

わざわざ回答、ありがとうございます。
だいぶ先の方でmax関数について説明があったのですね。
関数名から、おそらく・・・と推測はしていたのですが、max関数の微分のイメージが沸かなかったので、質問させて頂きました。
これからも粛々と学習を進めるようにします。

どうもありがとうございました。

石田利一

2021年2月15日(月) 14:14 kazuki kawahara <notifications@github.com>:
