### ISSUE TITLE
「質問」モダンなWeb開発コース　簡易ECサイトのセットアップ

### ISSUE THREAD

**Issue by hiroshi0511** [kikagaku/kikagaku-public-issues#18]
楽しい講義ありがとうございます。
上記で、vue.jsの実装をMacのVscodeで実装しているのですが、
vue.jsが読み込めていないのか、バインディングできません。

ローカルで実行すると
{{title}}
{{price}}
と表示されてしまいます。

基本的にコピペしただけのはずなのですが、うまくできていないポイント
があるようです。

改善すべきポイントを教えていただけないでしょうか？

> [コード](url)
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>キカガクオンラインの動画販売ページ</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    
    <link rel="stylesheet" href="https://unpkg.com/jpn.css@latest/dist/bootstrap/jpn.min.css" />
</head>

<body>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">キカガクオンライン</h1>
    </div>
    
    <div class="container" id="app"></div>

    <div class="card-deck mb-4 text-center">
        
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{title}}</h4>
            </div>
            <img class="bd-placeholder-img card-img-top" width="100%" :src="img" />
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{price}}円</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>AI技術や数学について体系的に学びたい方</li>
                    <li>Python・機械学習の基礎を学びたい方</li>
                    <li>AI開発の全体像を知りたい方</li>
                </ul>
                <button type="button" :class="btnType">カートに入れる</button>
            </div>
        </div>
    </div>
    <footer class="border-top mt-5">
        <small class="d-block mb-3 text-muted">©キカガク</small>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    
    <script>
        const app = new Vue({
            // id = app の要素内で Vue の機能が使えるように設定
            el: '#app',
            data: {
                title: '【初級】機械学習',
                img: 'https://web-source.kikagaku.net/ikusai-web-3-0.png',
                price: 10000,
                btnType: 'btn btn-lg tbn-block btn-info',
            },
        })
    </script>
</body>

</html>

**Comment by kazuki-310** [comment]
モダンなWeb開発コースを受講いただきありがとうございます！

```html
<div class="container" id="app">
```
上記のコードは記載されてますでしょうか？
一度確認してみて下さい。

引き続きよろしくお願い致します。

**Comment by hiroshi0511** [comment]
ありがとうございます。
id = appは記載しておりますが、状況は変わらないです。

<body>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">キカガクオンライン</h1>
    </div>
    
    <div class="container" id="app"></div>

    <div class="card-deck mb-4 text-center">
        
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal" id="app">{{title}}</h4>
            </div>
            <img class="bd-placeholder-img card-img-top" width="100%" :src="img" />
            <div class="card-body">
                <h1 class="card-title pricing-card-title" id="app">{{price}}円</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>AI技術や数学について体系的に学びたい方</li>
                    <li>Python・機械学習の基礎を学びたい方</li>
                    <li>AI開発の全体像を知りたい方</li>
                </ul>
                <button type="button" :class="btnType">カートに入れる</button>
            </div>
        </div>
    </div>
    <footer class="border-top mt-5">
        <small class="d-block mb-3 text-muted">©キカガク</small>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    
    <script>
        const app = new Vue({
            // id = app の要素内で Vue の機能が使えるように設定
            el: '#app',
            data: {
                title: '【初級】機械学習',
                img: 'https://web-source.kikagaku.net/ikusai-web-3-0.png',
                price: 10000,
                btnType: 'btn btn-lg tbn-block btn-info',
            },
        })
    </script>

**Comment by kazuki-310** [comment]
再度動画を見直して頂くと、うまくいかない原因がわかるかも知れないので挑戦してみて下さい。
引き続きよろしくお願いいたします。

**Comment by kazuki-310** [comment]
@hiroshi0511 
いつも【キカガク】で学習して頂きありがとうございます。

こちら質問ですが解決されましたでしょうか？
私の方では、上記のコードを試したところ問題なく動作は確認できましたので、下記のコードを参考に一度自身の書かれたコードと確認お願いできますでしょうか？

```html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>キカガクオンラインの動画販売ページ</title>
    <!-- Bootstrapのファイル読み込み -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />
    <!-- Bootstrapの日本語フォントを変換する外部ファイルの読み込み -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/jpn.css@latest/dist/bootstrap/jpn.min.css"
    />
  </head>
  <body>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">キカガクオンライン</h1>
    </div>

　<!-- こちらの id="app" は記載されてますでしょうか？ -->
    <div class="container" id="app">
      <div class="card-deck mb-4 text-center">
        <!-- カードタグ -->
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{title}}</h4>
          </div>
          <img
            class="bd-placeholder-img card-img-top"
            width="100%"
            :src="img"
          />
          <div class="card-body">
            <h1 class="card-title pricing-card-title">{{price}}円</h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>AI技術や数学について体系的に学びたい方</li>
              <li>Python・機械学習の基礎を学びたい方</li>
              <li>AI開発の全体像を知りたい方</li>
            </ul>
            <button type="button" :class="btnType">カートに入れる</button>
          </div>
        </div>
      </div>
      <footer class="border-top mt-5">
        <small class="d-block mb-3 text-muted">©キカガク</small>
      </footer>
    </div>

    <footer class="border-top mt-5">
      <small class="d-block mb-3 text-muted">©キカガク</small>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Vue 関連の記述箇所 -->
    <script>
      const app = new Vue({
        // id = app の要素内で Vue の機能が使えるように設定
        el: '#app',
        data: {
          title: '【初級】機械学習',
          img: 'https://web-source.kikagaku.net/ikusai-web-3-0.png',
          price: 10000,
          btnType: 'btn btn-lg tbn-block btn-info',
        },
      })
    </script>
  </body>
</html>
```
また、わからない点があれば質問お待ちしております。
引き続きよろしくお願いいたします。
