### ISSUE TITLE
3-6. 交差エントロピーの式の符号に関して

### ISSUE THREAD

**Issue by mi-okada** [kikagaku/kikagaku-public-issues#19]
資料の最後に書かれております、
二値交差エントロピーの式の符号は”マイナス”ではないでしょうか。
![image](https://user-images.githubusercontent.com/79678331/109247953-36e60000-7828-11eb-9fb3-0d86b700bf97.png)

**Comment by kazuki-310** [comment]
脱ブラックコース受講いただきありがとうございます。
ご指摘頂いた通りマイナスが抜けておりました。

こちら修正いたしました。
https://www.kikagaku.ai/course/blackbox/learn/math-basic3/cross-entropy/

引き続きよろしくお願いいたします。
