### ISSUE TITLE
【質問】テスト誤記訂正依頼（脱ブラックボックス）

### ISSUE THREAD

**Issue by yuya-murakami** [kikagaku/kikagaku-public-issues#2]
脱ブラックボックスコースを受講中、誤記？と思われる個所を発見したので掲載します。

[https://www.kikagaku.ai/course/blackbox/learn/math-basic1/python-development1](url)

写真ではN = 1,2,3,3,3 ですが、実際はN = 1,2,3,4,5でしょうか？
![image](https://user-images.githubusercontent.com/77181430/104081203-8e2c1300-5270-11eb-9eee-839c0d7700e9.png)
お手数ですがご確認よろしくお願いします。

**Comment by yuya-murakami** [comment]
In this question , answer is -7. Combining the answer to question 2 with question 1, I'm guessing that question 2 is a question about finding the x-transposition w, not the w-transposition w.
(https://www.kikagaku.ai/course/blackbox/learn/math-basic2/multiple-regression)
![image](https://user-images.githubusercontent.com/77181430/104087532-be40d980-52a3-11eb-92aa-e1f81b89d248.png)

**Comment by yuya-murakami** [comment]
追加です。
(https://www.kikagaku.ai/course/blackbox/learn/math-basic3/cross-entropy)[url]
上記ページ問2、問4の答えはそれぞれ「75」であると思っていましたが、不正解とでました。
![image](https://user-images.githubusercontent.com/77181430/104124220-f07d3480-5392-11eb-8d82-2bac71215cbd.png)
![image](https://user-images.githubusercontent.com/77181430/104124221-f6731580-5392-11eb-83dc-972a48c1992b.png)

私の理解不足でしたら申し訳ありませんが、確認お願いします。

![image](https://user-images.githubusercontent.com/77181430/104124166-9bd9b980-5392-11eb-80c3-b6174936870b.png)

**Comment by kazuki-310** [comment]
対応遅れてしまい申し訳ありません。
すべて修正いたしましたのでご確認お願い致します。

引き続きよろしくお願い致します。
