### ISSUE TITLE
[質問]モダンなWEB開発　nuxtのfirebaseの導入

### ISSUE THREAD

**Issue by hiroshi0511** [kikagaku/kikagaku-public-issues#20]
お世話になっております。
２つ質問があります。
１）
nuxtでplugin/firebase.js を作成するところでエラーとなってしまいます。
'Replace '......' with '....'eslint(prettier/prettier)
というメッセージが、firebaseからコピーした設定の部分に出てしまいます。

        apiKey: 'AI',
        authDomain: 'fa',
        projectId: 'faq',
        storageBucket: 'faq',
        messagingSenderId: ',
        appId: '1:78',

具体的には上記のapiKeyの左に、VSCODEで〜〜〜〜が表示されエラーとなっています。

２）
Firebaseからの設定をコピーする手順で、講義資料にあるdatabaseURLがないのですが
設定を見逃しているのでしょうか？
動画通りにやっているつもりなのですが、上記１）のエラーと相まって先に進めません。
お手数ですがよろしくお願いします。

**Comment by kazuki-310** [comment]
お世話になります。

> nuxtでplugin/firebase.js を作成するところでエラーとなってしまいます。
> 'Replace '......' with '....'eslint(prettier/prettier)
> というメッセージが、firebaseからコピーした設定の部分に出てしまいます。

こちらに関しては、 eslint のエラーかと思われます。
ですので、前章での eslint の設定のところや、変なところに改行などが入ってないか一度見直してみて下さい。

> Firebaseからの設定をコピーする手順で、講義資料にあるdatabaseURLがないのですが
> 設定を見逃しているのでしょうか？
こちらは、現在デフォルトでは、 databaseURL は表示されませんので、databaseURL はここで記載していただかなくても大丈夫になります。

また、エラーがあった際は、エラー分をスクリーンショットなどと一緒に送っていただけるとこちらも現状を確認しやすくなりますので、お手数ですがその際はよろしくお願いいたします。

また、エラーが解決できなければ質問お待ちしてます。
