### ISSUE TITLE
【質問】2.7ベクトル関連の関数のテストについて　(脱ブラックボックスコース)

### ISSUE THREAD

**Issue by nijiro98** [kikagaku/kikagaku-public-issues#21]
こちらの解法につきまして、解説動画（数学の基礎step2）を見ても、ヒントを読んでも、どうにもさっぱりわかりません。
この場合、どのように前に進めばよろしいでしょうか？（追加ヒントはもらえないでしょうか？）

**Comment by nijiro98** [comment]
あとからすみません。行列の微分公式に関する情報のページ
http://arduinopid.web.fc2.com/N29.html
こちらを見ていたら、理解できました！

**Comment by kazuki-310** [comment]
脱ブラックコースを受講頂きありがとうございます。
無事解決されて素晴らしいです。

引き続きよろしくお願いします。
