### ISSUE TITLE
質問】2.7ベクトル関連の関数のテストについて　(脱ブラックボックスコース)

### ISSUE THREAD

**Issue by domy1980** [kikagaku/kikagaku-public-issues#23]
お世話になります。

y=max(0,u）

の式の意味がわかりません。
前の資料に出ているようでしたら、その参考の部分か、
または追加の解説・注釈など、教えて頂ければ幸いです。
宜しくお願い致します。

**Comment by domy1980** [comment]
後から失礼します、私もできました。
ですが、式の説明がpoor過ぎると思います。
または、事前知識でここまでなければ出来ない点をきちんと記載すべきだと思います。
初学者にとって、わかりにくい資料は、時間泥棒になり得ます。
宜しくお願い致します。

**Comment by kazuki-310** [comment]
脱ブラックコースを受講いただきありがとうございます。
また、ご質問頂きありがとうございます！

> y=max(0,u)
> という関数が唐突に出てきますが、この関数の定義は何でしょうか?

こちら解決されてよかったです。
また、下記の章で詳しく説明してますので、今後の勉強の際に参考にして頂けたらと思います。
https://www.kikagaku.ai/course/blackbox/learn/nn-math/fp-nonlinear-transformation/

> または、事前知識でここまでなければ出来ない点をきちんと記載すべきだと思います。
> 初学者にとって、わかりにくい資料は、時間泥棒になり得ます。

貴重なご意見頂きありがとうございます。
こちら社内で検討し、より分かりやすい資料にしていきたいと思います。
今後ともよろしくお願い致します。
