### ISSUE TITLE
脱ブラックボックスコース / 数学の基礎(step3) / 期待値 / テスト

### ISSUE THREAD

**Issue by aisobe** [kikagaku/kikagaku-public-issues#24]
Q1の確率P(x)全体ですが、100では無く１でしょうか？
確率を全部足すと１になります。

**Comment by kikagaku** [comment]
脱ブラックコースを受講いただきありがとうございます！

私の方で確認しましたが、解答の方に問題はありませんでした。
再度、資料の方を参考に学習して頂けたらと思います。

引き続きよろしくお願いします。
