### ISSUE TITLE
脱ブラックボックスコース>5-4. ネットワークの訓練>テスト パッケージバージョン

### ISSUE THREAD

**Issue by yoko-mai** [kikagaku/kikagaku-public-issues#26]
再現性のため、同じパッケージバージョンで実行する必要があるかと思いますが、以下の通り、既に作成時のバージョンが存在しなくなっているようです。

`!pip install -q torch==1.7.0+cu101`
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cu101 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0)
ERROR: No matching distribution found for torch==1.7.0+cu101

このため、torch==1.7.0 を指定して実行しましたが、（私のコードが間違っているせいか、判断できませんが、）Q1のみ不正解になります。
正解コードが、torch==1.7.0 でも、採点で正解となるかご確認いただけませんでしょうか。

**Comment by kikagaku** [comment]
脱ブラックコースを受講いただきありがとうございます。

```python
!pip install -q torch==1.7.0+cu101
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cu101 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0)
ERROR: No matching distribution found for torch==1.7.0+cu101
```
バージョンエラーについてご指摘頂きありがとうございます。
`torch==1.7.0` のバージョンを私の方で試してみた結果、`torch==1.7.0+cu101`  と同様の解答になりバージョンによる解答の差は見られませんでした。
どこかでミスがあるかも知れませんので、再度見直して頂けたらと思います。

引き続きよろしくおねがいします。

**Comment by yoko-mai** [comment]
ご確認いただき、ありがとうございます。
> torch==1.7.0 のバージョンを私の方で試してみた結果、torch==1.7.0+cu101 と同様の解答になりバージョンによる解答の差は見られませんでした。
> どこかでミスがあるかも知れませんので、再度見直して頂けたらと思います。

改めて見直してみます。
以上、よろしくお願いいたします。

     ----- Original Message -----
 From: kikagaku ***@***.***>
 To: kikagaku/kikagaku-public-issues ***@***.***> 
Cc: yoko-mai ***@***.***>; Author ***@***.***>
 Date: 2021/3/15, Mon 21:08
 Subject: Re: [kikagaku/kikagaku-public-issues] 脱ブラックボックスコース>5-4. ネットワークの訓練>テスト パッケージバージョン (#26)
   
脱ブラックコースを受講いただきありがとうございます。!pip install -q torch==1.7.0+cu101
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cu101 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0)
ERROR: No matching distribution found for torch==1.7.0+cu101バージョンエラーについてご指摘頂きありがとうございます。
torch==1.7.0 のバージョンを私の方で試してみた結果、torch==1.7.0+cu101 と同様の解答になりバージョンによる解答の差は見られませんでした。
どこかでミスがあるかも知れませんので、再度見直して頂けたらと思います。引き続きよろしくおねがいします。—

**Comment by yoko-mai** [comment]
改めて確認しましたが、誤りが見つかりません。
コードに本当に誤りがないかは不明ですが、そもそも正解コードは一意には決まりません。
なるべく資料と一致するようにコピー＆ペーストで作成したのですが、本質的な誤りではなくて、ほんの少し処理手順が異なるだけなのかもしれません。

そこで、以下について、確認させてください。

1．乱数種固定タイミング

　資料と同様に以下の2か所でよろしいでしょうか？

①データセット分割直前
②ネットワークのインスタンス作成直前

各種データセットの検証前にも固定したくなりますが、資料に合わせて固定しないで実行しています。各種データセットの検証前に固定する場合も試しましたが、不正解のままでした。

2．学習ループの正解率出力

資料終わりのように、学習ループで正解率を出力していますか？

３．各種データセットの評価順序

設問と同じように、訓練データ、検証データ、テストデータの順でよろしいでしょうか？

**Comment by kikagaku** [comment]
ご質問頂きありがとうございます。
乱数固定のタイミングは資料と同じで問題ありません。

おそらく余計なコードが入力されている可能性が考えられますね。
下記のコードを参考にもう一度見直してみて頂けたらと思います。

```Python
class Net(nn.Module):
    def __init__(self):

その他、作成必要。
```
```python
torch.manual_seed(0)
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
max_epoch = 5
net = Net().to(device)
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

for epoch in range(max_epoch):
    for batch in train_loader:

        x, t = batch
        x = x.to(device)
        t = t.to(device)
        y = net(x)
        loss = F.cross_entropy(y, t)

        # 正解率の算出を追加
        y_label = torch.argmax(y, dim=1)
        accuracy = (y_label == t).sum().float() / len(t)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

print(f'accuracy: {accuracy:.4f}')
```

**Comment by yoko-mai** [comment]
ありがとうございます。

提示していただいたコードを使用して正解になりました。

ただし、上のコードは適切でないように思います。
設問では「訓練データ (train_loader) に対する正解率」を要求していますが、訓練ループに最終バッチに対する正解率になっています。つまり、訓練データをバッチサイズ分、10件しか使用していません。

**Comment by kikagaku** [comment]
ご指摘いただきありがとうございます。
この度はご不便おかけし申し訳ございません。
本件、ご指摘の通りでしたので、解答を修正いたしました。
