### ISSUE TITLE
脱ブラックボックスコース　2-6. ベクトルによる微分と勾配

### ISSUE THREAD

**Issue by ymiya55** [kikagaku/kikagaku-public-issues#27]
Q3の問題文が間違い。全体に2をかける必要があります。

**Comment by kikagaku** [comment]
ご質問頂きありがとうございます。
>Q3の問題文が間違い。全体に2をかける必要があります。

こちらは、2-6. ベクトルによる微分と勾配の Q3 の問題で合ってますでしょうか？
もう少し質問を詳細に記載いただけると解答できるかと思いますので、お手すきの際にご協力お願いいたします。

**Comment by ymiya55** [comment]
こちらの早とちりでした。見直したら合ってました。失礼しました。

**Comment by ymiya55** [comment]
すみません。Q2についてです。
b = -2 X.T t とおいてwで微分するとb.Tとなり、 b.T =  -2 t.T X となるように思います。
ここで.Tというのは転置の意味です。
これで計算すると[-18, ?] の1行2列になりますが、問題文では2行1列になっています。
こちらの勘違いでしたらすみません。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。

こちら修正いたしました。引き続きよろしくお願いいたします。
