### ISSUE TITLE
脱ブラックボックスコース＞5-6. Optuna によるハイパーパラメータの最適化＞環境構築

### ISSUE THREAD

**Issue by syleir** [kikagaku/kikagaku-public-issues#28]
すでにissuesでご指摘の通り、現在のColab環境では講座の指定の環境構築が達成できず,
torch==1.7.0、optuna == 2.6.0 pytorch_lightning==1.2.4でしか構築できませんでした。
資料のコードをコピペしても、accuracyを最大化する学習率や層の深さなどで再現ができません。これは課題にも支障があると考えられますので、再現可能な環境構築法があればご教授お願いいたします。

**Comment by kikagaku** [comment]
ご報告いただき、ありがとうございます。この度はご迷惑をおかけしておりまして、失礼いたしました。

バージョン起因の問題は現在対応中です。対応完了次第ご案内いたしますので、ご不便をおかけしますが、お待ちいただけますと幸いです。

**Comment by kikagaku** [comment]
この度はご迷惑をおかけしておりまして、失礼いたしました。
バージョン起因による問題は修正いたしました。

お手すきの際に確認いただけると幸いです。
引き続きよろしくお願いいたします。
リンク：https://www.kikagaku.ai/course/blackbox/learn/nn-implementation/hyperparameter-optimization-optuna/
