### ISSUE TITLE
メディカルAI専門コース＞1-4 実践編　CIFAR10 ＞環境構築とaccuracy算出

### ISSUE THREAD

**Issue by naokitohda** [kikagaku/kikagaku-public-issues#31]
環境構築とaccuracy算出に関して質問です。
torch　1.7.1
torchvision　0.8.2
pytorch_lightning 1.1.0
こちらの条件でコピーペーストしてimportを試みましたが、pytorch_lightningのimport時にImportErrorが発生します。
ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol:

また、バージョンを新しくすることでimport自体は可能ですが、そうするとaccuracy算出時にValueErrorが発生します。
これは最後の出力におけるsoftmaxを省略しているため、predが0-1の範囲に入らない場合があることが原因だと思われます。
これらの解決策についてご教授頂けると幸いです。

**Comment by TouiNishikawa** [comment]
受講生ですが、応急措置ができたのでコメントしてみます。

以下のように修正すると、テストにも正解できました。
accuracyを求める用に、別でsoftmaxを使用して0-1に収めました。
pytorch_lightningは最新のものを使用しています。

```
class Net(pl.LightningModule):
    def __init__(self):
        super().__init__()
　　#省略
        self.sm = nn.Softmax(dim=1)

    def forward(self, x):
       #省略

    def training_step(self, batch, batch_idx):
        x, t = batch
        y = self(x)
        loss = F.cross_entropy(y, t)
        pred = self.sm(y)
        self.log('train_loss', loss, on_step=False, on_epoch=True, prog_bar=True)
        self.log('train_acc', accuracy(pred, t), on_step=False, on_epoch=True, prog_bar=True)
        return loss
```

**Comment by naokitohda** [comment]
無事正解できました。
自分がsoftmaxを使用した時は使用後の値をlossに反映させていたため、答えが合わなくて困っていました。
ありがとうございます。
