### ISSUE TITLE
脱ブラックボックス講座　5-6 のテストについて

### ISSUE THREAD

**Issue by s2000117** [kikagaku/kikagaku-public-issues#32]
テスト時における中間層のノード数はどのように扱えばよいでしょうか？
「動画中の調整値 99」, 「defaultの10」, もしくは「optimimer, lrとともにoptuna でパラメータの調整を行う」のいずれかでしょうか？

**Comment by kikagaku** [comment]
ご質問頂きありがとうございます。
中間層のノード数は講義資料通りの１０で問題ありません。

また、現在バージョン起因による問題により、解答も修正が必要になっております。
こちら現在対応中です。対応完了次第ご案内いたしますので、ご不便をおかけしますが、お待ちいただけますと幸いです。

**Comment by s2000117** [comment]
はい了解です。お待ちしております。

**Comment by kikagaku** [comment]
この度はご迷惑をおかけしておりまして、失礼いたしました。
バージョン起因による問題は修正いたしました。

お手すきの際に確認いただけると幸いです。
引き続きよろしくお願いいたします。
リンク：https://www.kikagaku.ai/course/blackbox/learn/nn-implementation/hyperparameter-optimization-optuna/
