### ISSUE TITLE
脱ブラックボックスコース＞5-5. PyTorch Lightning による簡略化＞環境構築

### ISSUE THREAD

**Issue by krasick** [kikagaku/kikagaku-public-issues#34]
1. !pip install -q pytorch_lightning==1.0.8をインストールした後、import pytorch_lightning as plでエラー (In [2])
ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)
（ここ最近Colabへのpytorch_lightningのインストールで不具合がみられるようです。）

2. 1.2.4やdev1.3.0ではimportできるので、そちらで続けていたところ、accuracy(y, t)のところでエラー (In [23])
ValueError: The `preds` should be probabilities, but values were detected outside of [0,1] range.
（>1.2以降では設計が異なるためのようです。これも最近報告されています。）

3. accuracy(y,t)を使わず、self.log('train_acc', accuracy(y, t), on_step=True, on_epoch=True, prog_bar=True)をコメントアウトして続けていたところ、callbacks=[EarlyStopping(monitor='val_loss')]でエラー (In [25])
RuntimeError: Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss_step`, `train_loss_epoch`, `train_loss`
（これも無理なバージョン選択によるものと推測していますが、よくわかりません。）

4. テストページのリンク（https://pytorch-lightning.readthedocs.io/en/latest/early_stopping.html）が切れています。

上記の不具合により、資料通りの実行が不可能でした。typoがないように参考資料をすべてコピペして改めて実行しましたが、同じエラーが出ました。私だけで生じているのかがわかりませんので、改めてご確認いただき、環境構築に関する追加説明、あるいは資料・テストの修正などのご対応をいただければと思います。よろしくお願いいたします。（したがって、現在5-6も実行が不可能です。）

**Comment by TouiNishikawa** [comment]
受講生です。
他のissueでも勝手ながら回答させていただきましたが、
応急措置になりますが、以下のように修正すると、
「1.2.4やdev1.3.0ではimportできるので、そちらで続けていたところ、accuracy(y, t)のところでエラー (In [23])」
はなくなり、このテストには正解できました。
softmax関数で[0,1] rangeに収めています。

```
class Net(pl.LightningModule):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(30, 10)
        self.bn1 = nn.BatchNorm1d(10)
        self.fc2 = nn.Linear(10, 2)
        self.sm = nn.Softmax(dim=1)


    def forward(self, x):
        h = self.fc1(x)
        h = F.relu(h)
        h = self.bn1(h)
        h = self.fc2(h)
        return h


    def training_step(self, batch, batch_idx):
        x, t = batch
        y = self(x)
        loss = F.cross_entropy(y, t)
        pred = self.sm(y)
        self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True)
        self.log('train_acc', accuracy(pred, t), on_step=True, on_epoch=True, prog_bar=True)
        return loss


    # 検証データに対する処理
    def validation_step(self, batch, batch_idx):
        x, t = batch
        y = self(x)
        loss = F.cross_entropy(y, t)
        pred = self.sm(y)
        self.log('val_loss', loss, on_step=False, on_epoch=True)
        self.log('val_acc', accuracy(pred, t), on_step=False, on_epoch=True)
        return loss


    # テストデータに対する処理
    def test_step(self, batch, batch_idx):
        x, t = batch
        y = self(x)
        loss = F.cross_entropy(y, t)
        pred = self.sm(y)
        self.log('test_loss', loss, on_step=False, on_epoch=True)
        self.log('test_acc', accuracy(pred, t), on_step=False, on_epoch=True)
        return loss


    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=0.01)
        return optimizer
```

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。この度はご迷惑をおかけしておりまして、失礼いたしました。
また TouiNishikawa 様、ご親切にありがとうございます。

環境構築やバージョン起因による問題は現在対応中です。対応完了次第ご案内いたしますので、ご不便をおかけしますが、お待ちいただけますと幸いです。

**Comment by kikagaku** [comment]
この度はご迷惑をおかけしておりまして、失礼いたしました。
バージョン起因による問題は修正いたしました。

お手すきの際に確認いただけると幸いです。
引き続きよろしくお願いいたします。
リンク：https://www.kikagaku.ai/course/blackbox/learn/nn-implementation/simplifying-pytorch-lightning/
