### ISSUE TITLE
一連のバージョン変更によるエラーについて（脱ブラックボックスコース / メディカルAI専門コース）

### ISSUE THREAD

**Issue by TouiNishikawa** [kikagaku/kikagaku-public-issues#35]
受講生です。
一連のバージョン変更によるエラーについて根本的な解決策があったので、記載します。

以下のようにpipすると、
import時にエラーが出ません。

脱ブラックボックスコース / メディカルAI専門コース
```
!pip install torchtext==0.8.0 torch==1.7.0 pytorch-lightning==1.0.8
```

メディカルAI専門コース(Faster R-CNN利用時など)
```
!pip install torchtext==0.8.0 torch==1.7.1 pytorch-lightning==1.1.0 torchvision==0.8.2
```

**Comment by kikagaku** [comment]
脱ブラックボックス、メディカルAI専門コースを受講いただきありがとうございます。
また、バージョン変更により迷惑をかけ申し訳ありません。
このような対応策まで記載していただきありがとうございます。

現在脱ブラックボックスコースに関してバージョン起因によるエラーは修正済みです。
メディカルAI専門コースも修正次第連絡いたしますので、お手数おかけしますがよろしくお願いいたします。
