### ISSUE TITLE
脱ブラックボックスコース　数学の基礎（Step3）交差エントロピー　Q1

### ISSUE THREAD

**Issue by domy1980** [kikagaku/kikagaku-public-issues#36]
お世話になります。
設問Q1ですが、日本語としての『目的語』がはっきり示されておりません。
（何を求めたら良いか？）
雰囲気ではわかりますが、直した方が親切かと思いました。
宜しくお願い致します。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、ご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/blackbox/learn/math-basic3/cross-entropy/

今後とも宜しくお願いいたします。
