### ISSUE TITLE
メディカルAI専門コース>4-4. ネットワークの定義と訓練>accuracy関数の挙動

### ISSUE THREAD

**Issue by syleir** [kikagaku/kikagaku-public-issues#37]
連日深夜までバージョン起因のエラー対応していただいていて感謝いたします。

たびたび申し訳ありません。ここでもバージョンの差異によると思われるpytorch_lighrning.metrics.functional 内のaccuracy関数が挙動がおかしく、訓練の実行時に　ValueError: The `target` has to be an integer tensor.とValue errorを吐いてしまいます。

データ型を弄るなど試してみましたが、どうも解決策がわからず、最新のバージョンでの書き方があればご教授お願いいたします。

**Comment by kikagaku** [comment]
ご報告いただき、ありがとうございます。この度はご迷惑をおかけしておりまして、失礼いたしました。

ご指摘頂いた問題含め、バージョン起因による問題は現在対応中です。対応完了次第ご案内いたしますので、ご不便をおかけしますが、お待ちいただけますと幸いです。

**Comment by kikagaku** [comment]
いつも学習していただきありがとうございます。
現在 Colaboratory にデフォルトで入っているパッケージバージョンに対応した資料にアップデートいたしました。
ご確認いただけますと幸いです。
