### ISSUE TITLE
脱ブラックボックスコース　数学の基礎（step2） ベクトルによる微分と勾配　テストQ2

### ISSUE THREAD

**Issue by kMaineCoon** [kikagaku/kikagaku-public-issues#38]
-2Xtwは行列の要素数が合わないため計算できません．

![スクリーンショット 2021-03-25 0 02 32](https://user-images.githubusercontent.com/79515071/112332875-73106180-8cfd-11eb-94e1-e7e13fc66e1a.png)

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、ご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/blackbox/learn/math-basic2/differentiation-gradient-vector/
