### ISSUE TITLE
GPUの切り替え方法について

### ISSUE THREAD

**Issue by DeepPharmacist** [kikagaku/kikagaku-public-issues#39]
日々勉強させていただいている初学者です。
GPUについて、「各課題での再現性確保のため”Telsa T4推奨”」との記載がありますが、昨日まではT4だったのですが、本日は、「Tesla P100-PCIE-16GB」と出てしまい、そのためか正解できません（原因がこのせいかは特定できていませんが）。Google ColaboratoryでのGPUを指定する（TeslaT4に切り替える）方法はあるのでしょうか？ググってもよくわかりませんでした。

**Comment by DeepPharmacist** [comment]
本日は、またT4に戻り、プログラム変更なしで、再実行により正解になりました。
今後のためにも、切り替え方法があるのであれば、教えていただきたいです。

**Comment by kikagaku** [comment]
ご質問いただきありがとうございます。

GoogleColaboratory では、デフォルトで GPU がランダムに設定されるようになっております。
そのためバージョンが異なった場合、ランタイムに再度接続し直していただくと割り当てられる GPU が変更されますので、その様に対応していただけると幸いです。
