### ISSUE TITLE
脱ブラックボックスコース　数学の基礎（step3）確率変数と確率分布

### ISSUE THREAD

**Issue by kMaineCoon** [kikagaku/kikagaku-public-issues#41]
講義資料と講義動画の正規分布の式が間違えています．
eの中のマイナスが抜けています．

![スクリーンショット 2021-03-28 11 32 02](https://user-images.githubusercontent.com/79515071/112740660-8f402700-8fb9-11eb-8e2c-0dc5a92dc5e8.png)

こちらが正しい式ではないですか？

![スクリーンショット 2021-03-28 11 34 46](https://user-images.githubusercontent.com/79515071/112740668-aaab3200-8fb9-11eb-937b-dd5894cbbfd6.png)

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、ご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/blackbox/learn/math-basic3/isolated-variables-probability-distributions/
