### ISSUE TITLE
脱ブラックボックスコース　ニューラルネットワーク（数学編）　ニューラルネットワークの基礎　テスト

### ISSUE THREAD

**Issue by kMaineCoon** [kikagaku/kikagaku-public-issues#42]
テストの解答を何を求めれば良いか不明瞭です．
「パラメータ（重みとバイアス）の総数」
と記載されていますが，答えは重みと隠れ層と出力層の数との和となっています．
「パラメータ（重み）と計算によって得られるノードの総数」というような表現に変えた方がいいと思います．

**Comment by kikagaku** [comment]
ご質問いただき、ありがとうございます。
本問題文に関しては、現在の表現で問題ないものとなっております。
テストの内容に関わるためご説明は出来ませんが、今一度資料を読み直していただけますと幸いです。

**Comment by kMaineCoon** [comment]
問題文にある「パラメータ（重みとバイアス）の総数」とはノード同士を繋ぐ線のことを指しているのですか？
もしそうであれば，「パラメータ（重みとバイアス）の総数」と答えは同じになりません．
