### ISSUE TITLE
5.4ネットワークの訓練（脱ブラックボックスコース）

### ISSUE THREAD

**Issue by domy1980** [kikagaku/kikagaku-public-issues#44]
お世話になります。
何度トライしても、テスラのR4になりません。
小数点第4位まで揃えた回答が出せずにいます。

資格に必要なテキスト（メディカルAI学会認定の一部として）とテストで、これは非常に問題だと思います。
また、他でも、バージョンの違いによる問題なども、updateされておりません。
無料とはいえ、学会と連動してされている資格に含まれており、社会人が時間をとって学んでいるところの時間を奪うのは非常に問題だと感じております。

また、過去に投稿し解決したと考えられる質問・回答などが消えております。これらを参考にしている人もいると思うので、残して頂きたいと思います。
何卒、ご対応をお願い出来れば幸いに存じます。宜しくお願い致します。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
ご迷惑お掛けし申し訳ありません。
こちら各コンテンツごとにお知らせタブを追加いたしましたので、そちらを参考に GPU を変更いただけますようお願いします。

また、過去に投稿した質問、回答に関しては closed タブから見ることが可能になっておりますので、そちらからご確認いただけると幸いです。
![スクリーンショット 2021-04-09 21 51 25](https://user-images.githubusercontent.com/28823042/114182629-ccbf8f80-997d-11eb-9631-79bad3bf9da8.png)
