### ISSUE TITLE
5.4ネットワークの訓練（脱ブラックボックスコース）

### ISSUE THREAD

**Issue by jinwatanabe** [kikagaku/kikagaku-public-issues#45]
質問させ頂きます。脱ブラックボックスコース毎日楽しく受けさせていただいています。

テストの問題1. 「訓練データ (train_loader) に対する正解率を小数第４位で答えなさい。」について質問があります。
こちらの問題だけが解けずに苦戦しているのですが、

```
train_loader = torch.utils.data.DataLoader(train, batch_size, shuffle=True, drop_last=True)
```

最後にこのようにして正解率を求めています。
```
calc_accuracy(train_loader)
```

またtrain_loaderはシャッフルされるため正解率が実行するたびに変わるのですが、正解は常に1つの値に定まるのでしょうか。
よろしくお願いします。

**Comment by kikagaku** [comment]
ご質問いただき、ありがとうございます。テストに関する内容ですのでコメントは控えますがご了承ください。解けない時にも次に進んでみるとヒントがあったり、思いついたりするものですので、諦めずに進めてみてください。

ヒント：シードの固定を行いましょう。
