### ISSUE TITLE
5-6. Optuna によるハイパーパラメータの最適化(脱ブラックボックスコース）

### ISSUE THREAD

**Issue by daito1999** [kikagaku/kikagaku-public-issues#46]
torchのバージョンが3月26日に変更になっているようです。
最新版の1.8.1を用いると最適化後のパラメーターが異なる結果になります。
おそらくloderの分割に影響していると思われます。
シードの固定などは授業資料と同じにしております。

!pip install -q torch==1.8.0+cu101と指定しても上手く以前のバージョンに変更できません。

1.8.1のバージョンのアンインストールから1.8.0への変更までの一連のコードを教えていただけますか？

**Comment by kikagaku** [comment]
ご教示いただき、ありがとうございます。
こちらは現在の最新バージョンでの実行結果を正解となるように修正いたしましたので、torch のバージョンは 1.8.0+cu101 で実行していただければ幸いです。
