### ISSUE TITLE
5-5. PyTorch Lightninig による簡略化

### ISSUE THREAD

**Issue by jinwatanabe** [kikagaku/kikagaku-public-issues#47]
いつも講義楽しく受けさせていただいております。
エラーが発生してしまい、テストが解けなかったため質問させいていただきます。

```
trainer = pl.Trainer( 必要な設定 , callbacks=[EarlyStopping(monitor='val_loss')])
```

このようにプログラムを書くと、以下のようなエラーがでてしまいます。

```
RuntimeError: Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss_step`, `train_acc_step`, `train_loss_epoch`, `train_acc_epoch`, `train_loss`, `train_acc`
1
```

`val_loss`が利用できないようです。
他のコードは講義と変更しておりません。どのように対処すればよいでしょうか。
よろしくお願いします。

**Comment by kikagaku** [comment]
ご質問いただき、ありがとうございます。テストに関する内容ですのでコメントは控えますがご了承ください。解けない時にも次に進んでみるとヒントがあったり、思いついたりするものですので、諦めずに進めてみてください。

（ヒント： trainer.fit の引数に val_loader を与えてみてください）
