### ISSUE TITLE
Chapter 5-4 (脱ブラックボックスコース)　 GPUの切り替えについて

### ISSUE THREAD

**Issue by iceryusuke** [kikagaku/kikagaku-public-issues#48]
初歩的な質問で大変申し訳ありません。
有償版のclab proを使用しているからかもしれませんが、GPUがT4になかなか切り替わりません。
ランタイムの初期化を繰り返すこと以外に、 GPUの指定はできますでしょうか。
ご教示のほど何卒よろしくお願いいたします。

**Comment by kikagaku** [comment]
脱ブラックボックスを受講いただきありがとうございます。

公式サイトを確認すると下記のように記載されており GPU の指定はおそらく出来ないかと思われます。
> Colab Pro に登録すると、最速の GPU を優先的に利用できます。

対応策としては、もう一つ Google のアカウントを作成していただき、そこで無料の colab を利用していただくと T4 を使用できるかと思いますので一度試していただけたらと思います。
ご迷惑をおかけし申し訳ありませんがよろしくお願いいたします。
