### ISSUE TITLE
脱ブラックボックスコース

### ISSUE THREAD

**Issue by arigedon** [kikagaku/kikagaku-public-issues#49]
楽しく受講させていただいております。本当にありがとうございます。さて、各レッスンのテストに関してお願いがあります。各レッスンのテストが過去正答した問題なのか、まだ未回答なのかを各テストごとに示していただけないでしょうか？学生進捗ページにいくとある程度は分かるのですが、どのレッスンのどのテストが未回答までは知ることができないようです。私の使い方が未熟でしたら申し訳ありません。その場合は、やり方を教えていただけますと幸いです。また意図的に正答した問題の復習を促すように、このようなシステムにされているのかもしれません。しかし社会人で仕事をしながら受講していますので、時間を有効に使いたいと思っています。可能でしたらご対応いただけますと嬉しいです。よろしくお願い致します。

**Comment by kikagaku** [comment]
脱ブラックボックスを受講いただきありがとうございます。
また、貴重なご意見いただきありがとうございます。

> 各レッスンのテストが過去正答した問題なのか、まだ未回答なのかを各テストごとに示していただけないでしょうか？

こちらの質問ですが、過去正解した問題は下図から確認することが可能になります。
![スクリーンショット 2021-04-15 9 18 07](https://user-images.githubusercontent.com/28823042/114796287-8a59e080-9dcb-11eb-9ded-fe207240c5c1.png)

また、未回答なのかは、現状確認することが出来ません。
こちらは、社内で検討し受講生の皆様に満足していただけるようなプラットフォームにしていきたいと思いますので、今後ともよろしくお願いいたします。

**Comment by arigedon** [comment]
大変丁寧なご返信ありがとうございます。お示しいただいた画面で確かめることは可能です。しかしこの画面上において、例えばニューラルネット（数学編）の５つのテストのうち３つのテストが完了していることは分かるのですが、具体的にどのテストが終了しているかを確認することはできません。したがって完了するためには全てのテスト（この場合５つのテスト）を改めて回答する必要がありますので、時間効率が悪くなっています。

また別件ですが、通勤時間を利用して、iPhone 8でオンライン受講していますが、テストの内容がすべて表示されず（画面から切れてしまっている）、問題を解くことができない場合があります。テスト番号を具体的に示す必要があるかと思いますが、まずはご報告させていただきます。必要に応じてテスト番号をご連絡いたします。ご対応いただけますととても嬉しいです。
