### ISSUE TITLE
chapter2.7 ベクトル関連の関数

### ISSUE THREAD

**Issue by BetchyTakehiro** [kikagaku/kikagaku-public-issues#5]
テスト問題がどうしても解けません。

![IMG_5766](https://user-images.githubusercontent.com/72541429/104087936-86876100-52a6-11eb-9057-4d12087ea9cf.jpg)
Lは二乗誤差からの出題なのかと思いましたが、y=max(0,u)となっており、
無理やり添付画像のように解いたら最後がスカラーではなくベクトルになりました。

どのように解いていけばいいのかが見当がつかないので、ヒントを頂きたいです。

**Comment by kikagaku** [comment]
ご質問いただき、ありがとうございます。
テストに関する内容ですのでコメントは控えますがご了承ください。
解けない時にも次に進んでみるとヒントがあったり、思いついたりするものですので、諦めずに進めてみてください。応援しています。
