### ISSUE TITLE
メディカルAI専門コース 5.4 Faster R-CNN のテスト

### ISSUE THREAD

**Issue by MasahitoKatsuki** [kikagaku/kikagaku-public-issues#50]
お世話になってます。
こちらのテスト、サンプルナンバーをtrain[1]にしてやっても、正しい答えが出ないと思うのですが、いかがでしょうか。例えば、問２の0.5以上の信頼値のオブジェクトは私の結果では３つ出てきますが、答えは３ではないですよね。
こちらの問題や答えがそもそもあっているかどうか確認いただけませんでしょうか。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、お手すきの際にご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/medical-ai/learn/cell-detection/faster-r-cnn/
