### ISSUE TITLE
メディカルAI専門コース３．５

### ISSUE THREAD

**Issue by yuseisb** [kikagaku/kikagaku-public-issues#51]
資料に従ってFocalLoss関数にyとt.unsqueeze(1)を入力すると以下のエラーメッセージが出ます。targetとinputが異なる形のためのようですが、どのように解決したら良いか教えてください。

AssertionError: ground truth has different shape (torch.Size([256, 1])) from input (torch.Size([256, 2]))

**Comment by MasahitoKatsuki** [comment]
私も同じことでこまっています。。。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、ご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/medical-ai/learn/monitoring-data/unbalanced-data/
