### ISSUE TITLE
メディカルAI専門コース_3-3. ネットワークの定義と訓練_テスト

### ISSUE THREAD

**Issue by ymtk00** [kikagaku/kikagaku-public-issues#52]
お世話になっております。
講義内容とても興味深く学ばせていただいております。

気になった点についてご質問させていただきます。

質問では、小数第２位（第３位切り捨て）で答えるように記載されていますが四捨五入で答えが正解になるように思います。
ご確認頂ければ幸いです。宜しくお願い致します。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、お手すきの際にご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/medical-ai/learn/monitoring-data/network-definition-training2/
