### ISSUE TITLE
5-4. ネットワークの訓練(脱ブラックボックスコース）

### ISSUE THREAD

**Issue by rensyusei** [kikagaku/kikagaku-public-issues#54]
日本メディカルAI学会の認定資格の受講生です。

本来難解な内容を分かりやすく説明頂け、AIの核心に触れられている思いで、
大変有難いです。
脱ブラックボックスコースの５－４ですが、
動画では、torch 1.7.0でご説明頂いていると思います。

先月末に、torch 1.8.1のリリースがされたようでして、
現在、google laboratories でも、デフォルトで、version 1.8.1がimportされてきています。

現在、講義資料のコマンドをコピーペーストで入力し、講義資料の再現をしようとしましても、資料で書かれている計算結果を得られません（ご指示の通り、Tesra T4の使用下です）。

5－4のテストをクリアできないのですが、torch 1.8. 1にて計算をしていることで、
テストで想定されている当初回答とずれている、ということはございますでしょうか。

また、torchのversionを, 講義のように1.7.0に選択できる方法がありましたら、
講義内容の再現練習のため、大変助かりまして、ご教示頂けますと有難いです。

ご検討願います。

**Comment by kikagaku** [comment]
ご質問いただき、ありがとうございます。本資料、テスト回答に関しては、現在のもので問題ないものとなっております。
同じセルを複数回実行したりすることで結果が変わることもありますのでご注意ください。
他のパッケージのバージョンとの兼ね合いで、torch を 1.7.0 にすることは難しい点もご了承願います。
引き続きがんばってください。応援しています。

**Comment by rensyusei** [comment]
ご確認を頂き、ありがとうございました。引き続き頑張ります。
