### ISSUE TITLE
3.5 情報理論　資料

### ISSUE THREAD

**Issue by arigedon** [kikagaku/kikagaku-public-issues#55]
大変楽しく勉強させていただいております。御礼申し上げます。
Wantedly注目度ランキング第１位、おめでとうございます。

さて、次の点は、ケアレスミスですが、念のためご報告させていただきます。

3.5 情報理論　資料の中ほど
「まず、確率が高いときに少ないビット数で確率が高いときに多いビット数となると、確率の逆数がヒントになりそうであり、それぞれの確率の逆数は、」
p(x = 曇り）= 0.5 ですが p(x = 曇り）= 0.25 だと思います。

ご確認のほど、どうぞよろしくお願いいたします。

引き続きどうぞよろしくお願いいたします。

**Comment by kikagaku** [comment]
ご指摘いただき、ありがとうございます。
こちら修正いたしましたので、お手すきの際にご確認お願いいたします。

リンク：https://www.kikagaku.ai/course/blackbox/learn/math-basic3/information-theory/
