### ISSUE TITLE
メディカルAI専門コース>性能改善 : ファインチューニング

### ISSUE THREAD

**Issue by jinwatanabe** [kikagaku/kikagaku-public-issues#56]
テストについて気になった点がありましたので、報告させていただきます。

1. MobileNet v2のリンクが切れております。
おそらくこちらのリンクに変わっているかと思います。
https://pytorch.org/hub/pytorch_vision_mobilenet_v2/

2. パラメータの総数を確認するヒントがこのままではエラーが出てしまいます。

エラー内容
```
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

このように修正して回避しました。
```
# ヒント 
from torchsummary import summary
net = mobilenet_v2(pretrained=True)
net.to("cuda:0")
summary(net, (3, 224, 224))
```

こちらはテストの答える部分でないと思ったため報告させていただきました。
よろしくお願いします。

**Comment by Ayumukoike** [comment]
jinwatanabe 様
ご報告いただきましてありがとうございます。
リンクとヒントの削除、訂正を完了しましたのでご報告致します。
引き継ぎ宜しくお願い致します。
