### ISSUE TITLE
【Typo?】1-8. 最適なパラメータを求める

### ISSUE THREAD

**Issue by n-ohara** [kikagaku/kikagaku-public-issues#58]
ビデオ10:00頃からの手書き数式（最下行）は2乗が不要ではないでしょうか（仮に必要ということであれば、対応する資料の下から10行目の修正が必要となるのではないでしょうか）。
`

**Comment by nakabeppu** [comment]
@n-ohara さん
ご指摘ありがとうございます。
ご指摘の通り、動画の 2 乗が不要です。
資料が正確な計算式となります。
