### ISSUE TITLE
[質問]イントロダクションについて（Python&機械学習入門）

### ISSUE THREAD

**Issue by yjnmk** [kikagaku/kikagaku-public-issues#59]
イントロダクションの動画を見たのですが、
「脱ブラックボックス講座の中級編」のイントロダクションと言っていました。

動画の紐付けが変わってしまったのでしょうか？

よろしくおねがいします。

**Comment by nakabeppu** [comment]
@yjnmk さん
お世話になっております。
以前 Udemy、その他各セミナーで提供していた「脱ブラックボックス講座初級編、中級編」の内容をもとに作成しているため動画のような表現をさせていただいております。
