### ISSUE TITLE
【誤記の訂正依頼】テストの問題の文言の誤り

### ISSUE THREAD

**Issue by TownBeginner** [kikagaku/kikagaku-public-issues#6]
大変細かい話ですが、テストの問が「～を求め【なさい】」ではなく「～を求め【さない】」になっています。

https://www.kikagaku.ai/course/blackbox/learn/math-basic1/differentiation-of-composite-function
の「合成関数の微分」で気づきました。
お時間のある時に、修正をお願いできませんでしょうか。

**Comment by kazuki-310** [comment]
ご指摘頂きありがとうございます。
こちら修正致しました。

また、学習していく中で気になる点があれば遠慮なくご指摘頂けますと幸いです。
引き続きよろしくお願い致します。
