### ISSUE TITLE
【質問】メディカルAI専門コース【2-7.　最適化のカスタマイズ】

### ISSUE THREAD

**Issue by Ryowmu07** [kikagaku/kikagaku-public-issues#60]
いつも大変ためになる講義をありがとうございます。
初学者ではありますが、JMAIの資格取得を契機に貴社の講義で勉強出来たおかげで、理解が深まりました。

さて、本題となりますが、学会資格取得のために全ての講座受講が終了し、どうしても解けない問題が1題だけあります。2-7Q2「Q１ を参照に、ハイパーパラメータの最適化を行って得られた最適な gamma を小数第５位（小数第６位を四捨五入）で求めよ。」です。
原因としては、GPUはTesla T4を使用しておりますが、pytorch_lightningが1.1.0を指定してインストールできないために、gammmaの値がずれているのではないかと考えております。単純に私の技量不足によるところかもしれませんが、一度ご確認頂けたく連絡をさせて頂いました。現在のversionでも正答になるような修正や、対応方法などあればご教授いただければ幸いです。
よろしくお願い申し上げます。

**Comment by nn-byte** [comment]
私も同じく、2-7Q2がどうしても解けない状況に困っており、
Ryowmu07さんの指摘と同様の部分を疑っております。

**Comment by Ryowmu07** [comment]
ご多忙のところ、申し訳ありませんが、リマインドを込めて再度投稿させていただきます。
私以外にも困っている方がいるようですので、ご回答のほどよろしくお願い申し上げます。

**Comment by nn-byte** [comment]
お忙しいところ、私からも申し訳ございません。

質問させていただいている問題の前節の問題「2-6. ネットワークの訓練 Q1、Q2」や
「2-7. 最適化のカスタマイズ Q1」
その他にもハイパーパラメータの最適化は求める問いは設けられておりますが、
そちらは資料に従いoptunaを動作させると、数値が導き出されました。

一方、2-7Q2「Q１ を参照に、ハイパーパラメータの最適化を行って得られた最適な gamma を小数第５位（小数第６位を四捨五入）で求めよ。」については何度行っても同じ数値が算出されますが、正当が得られない状況です。

そのため数値のズレを疑っています。一度ご確認いただけますと幸いです。
よろしくお願い致します。

**Comment by nakabeppu** [comment]
対応が遅くなり大変申し訳ございません。
ご迷惑おかけしますが、確認後に再度ご連絡差し上げます。

**Comment by Ryowmu07** [comment]
ご連絡いただき、感謝申し上げます。
このテスト以外は合格しているので、このテストのみで1カ月近くとまっております。
お忙しいところ、恐縮ではありますが、よろしくお願い申し上げます。

**Comment by coolundertree** [comment]
こちらで確認したところ、解答に誤りがありました。
誠に申し訳ございませんでした。
システムを修正いたしましたので、再度ご入力し、結果をご確認ください。

不手際により、ご迷惑をおかけしたこと、重ねてお詫び申し上げます。
今後とも何卒よろしくお願い申し上げます。

**Comment by nn-byte** [comment]
ご対応いただきありがとうございます。
正解することができ、理解が間違っていなかったことに安堵致しました。

AI学習についてはまだまだ素人ではありますが、ポイントを押さえた非常に役に立つ内容に感銘しながら勉強してまいりました。これを機会に再度復習し、その他の教材も視野に入れていきたいと考えています。

誠にありがとうございました。
