### ISSUE TITLE
【質問】2-5. 線形結合と二次形式（脱ブラックボックスコース）

### ISSUE THREAD

**Issue by jun-tsuchiya** [kikagaku/kikagaku-public-issues#61]
初歩の初歩な質問で申し訳ありません。
掲題のチャプターのテストの回答がわかりません。
単純にxの値を代入して計算すると「62」になるのですが定数が残り、
「62+c」と回答すると「形式が違います」と言われます。
動画を何度もみましたがよくわかりませんでした。

ご教授をお願い致します。

![線形結合と2次形式_テスト](https://user-images.githubusercontent.com/18659788/118210002-b8067800-b4a4-11eb-8ecb-777407e5bc10.png)

**Comment by nakabeppu** [comment]
こちらはテストに関する質問となるため、申し訳ございませんが、回答は控えさせていただきます。
こちらのテストに関して、条件に不備等はございませんのでもう一度条件を確認して挑戦していただければと思います。
