### ISSUE TITLE
数学の基礎Step1の設問Q3について

### ISSUE THREAD

**Issue by okitajo** [kikagaku/kikagaku-public-issues#7]
https://www.kikagaku.ai/course/blackbox/learn/math-basic1/function-symbol
でテストタブを開き、テスト設問のテストQ3　について。

答えが1　とのことですが、その答えが導き出せません。

問題文の数式では、本来マイナス記号が表記されるべきところにそれが表記されていないためではないでしょうか。

![キカガク｜AI・機械学習を学ぶ_e_ラーニングプラットフォーム___キカガク](https://user-images.githubusercontent.com/53364269/104791470-86c3b700-57e6-11eb-820d-ec5d50c9b6bb.png)

よろしくお願いします。

**Comment by Jei-Kei** [comment]
キカガク運営様

お世話になります。

okitajo様のご指摘と同様の現象がこちらの受講中にも発生しました。
1.3章「微分の公式」のQ2で、問の行、ヒント行ともにマイナスが見えない場合があります。
＃使用ブラウザ：Vivaldi 3.5.2115.81で、ウインドウサイズ等？で発生状況変わります。

本件試行錯誤していたところ、どうも、数式表示エンジン？の都合によるもののようで、
数式上で右クリック→Math Settings→Math RendererをHTML-CSS等に変更することで
マイナス記号が安定に表示されるようになりました。

以上、取り急ぎご連絡いたします。

**Comment by okitajo** [comment]
Jei-Kei様ご指摘ありがとうございました。
私のブラウザでは、
数式上で右クリック→Math Settings→Math Renderer→SVGが選ばれておりまして、
この現象が発生していたようです。
ご指摘の通り、Math RendererをHTML-CSS等に変更することでマイナス記号が安定に表示されるようになりました。
