### ISSUE TITLE
脱ブラックボックスコース（2-11.Python で実装２）のテストについて

### ISSUE THREAD

**Issue by holys519** [kikagaku/kikagaku-public-issues#70]
問題２のxが明示されていますが、２行１列となっていますが、計算可能でしょうか？
ご回答お願いします。
<img width="843" alt="スクリーンショット 2021-05-28 13 23 26" src="https://user-images.githubusercontent.com/68938511/119929130-e6fa0f00-bfb7-11eb-9a54-56b4d7dde857.png">

**Comment by nakabeppu** [comment]
こちら、修正が完了しました。
ご指摘ありがとうございます。
