### ISSUE TITLE
メディカルAI専門コース【3-3 ネットワークの定義と訓練】と【3-4 残差学習】の評価基準が違います

### ISSUE THREAD

**Issue by KK-Saito** [kikagaku/kikagaku-public-issues#71]
【3-3. ネットワークの定義と訓練】のテストQ1の感度(＝recall)の値はプログラムの実行結果とは違った値が正解となっていますが，【3-4. 残差学習】のテストQ1ではプログラムの実行結果の値が正解となっています。
混同行列の右下をTrue Positiveとするか左上をTrue Positiveとするかで違ってくるわけですが，どちらかに統一する必要があります。
ビデオでは右下をTrue Positiveと説明していますが，左上をTrue Positiveとするのが一般的ですので，【3-4. 残差学習】の方に統一した方が良いと思います。
この場合，ビデオも修正する必要があると思います。

**Comment by KK-Saito** [comment]
もう一度確認してみましたが，やはり【3-3. ネットワークの定義と訓練】のテストQ1の感度(＝recall)の値はプログラムの実行結果とは違った値が正解となっていますが，【3-4. 残差学習】のテストQ1ではプログラムの実行結果の値が正解となっています。
ただし，どうやら【3-3. ネットワークの定義と訓練】のテストQ1では混同行列の左上をTrue Positiveとしているのに対して，【3-4. 残差学習】のテストQ1では混同行列の右下をTrue Positiveとしているようです。
基準が違うのはおかしいので，どちらかに統一した方が良いと思います。

**Comment by coolundertree** [comment]
ご連絡ありがとうございます。
ご指摘の通りですので、社内でどのように統一するか確認後、直ちに資料を修正いたします。

有益なご指摘大変助かりました、誠にありがとうございます。
今後とも何卒よろしくお願い申し上げます。
