### ISSUE TITLE
メディカルAI専門コース【1-4 実践編：CIFAR 10】のテストの2ブロック目の畳み込み層の数値について

### ISSUE THREAD

**Issue by KK-Saito** [kikagaku/kikagaku-public-issues#72]
【1-4 実践編：CIFAR 10】のテストの要件に，2ブロック目の畳み込み層の入力が(6, 32, 32)となっています。
しかし，直前の1ブロック目の最後の最大値プーリング層の出力が(6, 16, 16)ですので，2ブロック目の畳み込み層の入力は(6, 16, 16)でなければならないと思うのですが，違うのでしょうか？
実際に2ブロック目の畳み込み層の入力を(6, 16, 16)としてプログラミングしたのですが，答えが違うと判定されてしまいます。

**Comment by coolundertree** [comment]
貴重なご指摘ありがとうございました。
おっしゃる通り、テストの要件が誤っておりましたので、資料を修正いたしました。
大変助かりました。

ただし、今回の課題に関して、影響はありません。
cnnの入力には画像サイズは含まれないことを踏まえてもう一度挑戦してみてください。

何かありましたらいつでもご連絡ください。
よろしくお願いいたします。

**Comment by KK-Saito** [comment]
もう一度実行してみたのですが，やはりQ3の答えが間違っていると判断されてしまいます。
Q4の答えは正解していますので，ネットワーク構造は合っているはずです。
GPUも Tesla T4 を使っていますので，Q3も正解しているはずなのですが。

**Comment by coolundertree** [comment]
ご連絡が遅くなり、大変申し訳ありません。
こちら、Colab内の仕様の変更などで、正解の値が変更になっている可能性があります。
弊社でもう一度精査次第、ご連絡差し上げますので、少々お待ち下さい。
重ね重ねになりますが、混乱を招いてしまい、大変申し訳ありませんでした。
よろしくお願いいたします。

**Comment by coolundertree** [comment]
こちら、値を更新いたしましたので、もう一度入力していただけますでしょうか。
お手数おかけして申し訳ありませんが、よろしくお願いいたします。

**Comment by KK-Saito** [comment]
前回と同じ数値を入力したところ，今度は正解と判定されました。
メディカルAI学会の公認資格取得のためには全てのテストに合格する必要があるとのことですので，こういった間違いは致命的だと思います。

**Comment by coolundertree** [comment]
大変申し訳ありませんでした。
今後はこれまで以上に注意を払い、コンテンツをレビューしていきます。
貴重なご意見誠にありがとうございました。
今後とも宜しくお願い致します。
