### ISSUE TITLE
(質問)："Optuna"によるハイパーパラメータの最適化（テスト）

### ISSUE THREAD

**Issue by 0browns16** [kikagaku/kikagaku-public-issues#73]
テスト要件に沿って出力された結果から、最適なアルゴリズムの正解はできたが、学習率("lr")の正解は一致しませんでした。
試しに資料に掲載されているコードをそのまま出力すると、学習率("lr")の値が一致しない箇所が確認されました。
※
これは"optuna"等のライブラリのパージョンが異なるために発生しているのでしょうか？
またこれらによって、テストの回答に弊害が生じているのでしょうか？

![5-6-4  学習係数を最適化](https://user-images.githubusercontent.com/64362351/120895002-0e0aad80-c656-11eb-9e49-bdba14bedcc5.jpg)
![5-6-5  中間層のノード数を最適化](https://user-images.githubusercontent.com/64362351/120895003-106d0780-c656-11eb-9c99-d4def4d2203f.jpg)
![5-6-6  中間層の数を最適化](https://user-images.githubusercontent.com/64362351/120895007-14008e80-c656-11eb-9390-d7393363ef83.jpg)

**Comment by nihondaiho12** [comment]
私も同じ状態で先に進めず、困っています。（Optuna  v2.8.0   Pytorch v 1.8.1 +cu101, PytorchLightning  v 1.3.5 ）
PytorchLightningのバージョンを合わせるためにv1.0.8をgoogle colabでインストールしようとしたのですが、import時にエラーになってしまいます。
