### ISSUE TITLE
メディカルAI専門コース[1-3] ネットワークの定義と訓練について

### ISSUE THREAD

**Issue by 0browns16** [kikagaku/kikagaku-public-issues#77]
お世話になっております。
テスト(Q1,3)について質問です。
Q2のみ正解ができたのですが、Q1/Q3が正解できません。

念のためサンプルコード(資料)に沿ってコードを確認してみると一部の数値が再現できませんでした。([画像]テストデータに対する正解率の値)

試行した際のバージョンの違いがテストの正解値の計算に影響することがあるのでしょうか？
テストに関する質問なので、解答いただける範囲で教えていただけると幸いです。

(試行した際のバージョン)
　torch.__version__ (1.9.0+cu102)
　torchvision.__version__  (0.10.0+cu102)
　pl.__version__ (1.3.7post0)

![メディカルAI専門コース 1-3  ネットワークの定義と訓練について](https://user-images.githubusercontent.com/64362351/123911628-fdc8c280-d9b6-11eb-8496-e9716f724906.JPG)

**Comment by coolundertree** [comment]
連絡が遅くなり大変申し訳ありません。
精度はバージョンによって、影響を受けてしまう恐れがあります。私共の方で値を再確認してみます。
ご不便おかけして大変申し訳ありませんが、少々お待ち下さい。

**Comment by coolundertree** [comment]
続けての連絡失礼いたします。
1-3 Q3 に関しては、バージョンやコーディングに依存しない部分ですので、そちらは再度挑戦してみてください。
また、それに伴って、Q1のコーディングが誤っている可能性もありますので、何かありましたら再度ご質問ください。

引き続きこちらで、結果が変更になっていないか精査してまいります。
よろしくお願いいたします。

**Comment by 0browns16** [comment]
了解しました。対応して頂きありがとうございました。
