### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by YJYDM** [kikagaku/kikagaku-public-issues#8]
人生初のissueの為、過不足有ればご容赦下さい。
説明文の途中の付属資料のURL、リンクが切れている様です。

章題3-9. Python で実装

該当箇所

![image](https://user-images.githubusercontent.com/65581404/105568131-6a8dc000-5d7a-11eb-9a85-298ccbb91e04.jpeg)

適切なリンク

https://free.kikagaku.ai/tutorial/basic_of_machine_learning/learn/machine_learning_classification

ご査収下さい。

無料でここまで勉強出来て、感謝感激しています。

**Comment by kazuki-310** [comment]
この度はご指摘頂きありがとうございます
また、適切なリンクまで調べて頂きありがとうございます。

こちら修正致しました。
引き続きよろしくお願い致します。
