### ISSUE TITLE
【テスト解答ミスの可能性】メディカルAI専門コース　5-7. 性能改善：データ拡張

### ISSUE THREAD

**Issue by ayamazaki** [kikagaku/kikagaku-public-issues#80]
お世話になっております。

こちらのセクションのテストのうち、Q1,Q2,Q7,Q8解答の数字が間違っていると思われますのでご連絡を差し上げました。
Q3~Q6は正しいと思われる値で正解になるのですが、上記の4問については正しいと思われる値を入れても不正解となりました。

下記が正しい答えかと思われますので、修正をお願い致します。

Q1：621
Q2：631
Q7：461
Q8：471

どうぞよろしくお願致します。

**Comment by ayamazaki** [comment]
すみません追記です。
Q1Q2については、問題文から、ｘが9~19の範囲に広がっている物体を、x=0～640の範囲に広がる画像の中央であるx=320を軸として折り返した状況を考えて上記記載させていただいております。
もし上記の理解で間違っておりましたら、どの箇所が間違っているかご指摘をいただけますと幸いです。

**Comment by kikagaku-maruyama** [comment]
コードを含め丁寧にご説明いただきありがとうございます。
社内で改めて確認しましたところ、ayamazaki 様のご指摘の通りという結論となりました。

現在テスト回答は修正しております。
この度はご迷惑をおかけしまして失礼いたしました。
またご指摘ありがとうございました。
