### ISSUE TITLE
【Typo】『1-1-2. 指数関数と対数関数』のべき乗が負の数のときの計算式が誤っている（脱ブラックボックスコース）

### ISSUE THREAD

**Issue by nnDropout1** [kikagaku/kikagaku-public-issues#9]
[脱ブラックボックスコースの1-1. 本講座で登場する関数と記号](https://www.kikagaku.ai/course/blackbox/learn/math-basic1/function-symbol)の『1-1-2. 指数関数と対数関数』に以下のように書かれています。

<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Beqnarray%2A%7D%0A++%26%26+a%5En+%3D+%5Cfrac%7B1%7D%7Ba%5En%7D%0A%5Cend%7Beqnarray%2A%7D" 
alt="\begin{eqnarray*}
  && a^n = \frac{1}{a^n}
\end{eqnarray*}">

実際は以下の通りではないでしょうか？動画の06:03～あたりでもそのように説明されています。

<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Beqnarray%2A%7D%0A++%26%26+a%5E%7B-n%7D+%3D+%5Cfrac%7B1%7D%7Ba%5En%7D%0A%5Cend%7Beqnarray%2A%7D%0A" 
alt="\begin{eqnarray*}
  && a^{-n} = \frac{1}{a^n}
\end{eqnarray*}
">

ご対応を宜しくおねがいいたします。私の勘違いでしたら申し訳ありません。

**Comment by kazuki-310** [comment]
ご指摘頂きありがとうございます。
こちらブラウザやウィンドウのサイズによってはうまく表示されない不具合が見られます。

一旦は下記リンクを参照にご対応頂けますと幸いです。
また、原因が分かり次第対応致します。
https://github.com/kikagaku/kikagaku-public-issues/issues/7#issuecomment-761888694

**Comment by nnDropout1** [comment]
@kazuki-310 
ご対応をありがとうございます。ご案内いただいたリンクを参考に対処しました。

※環境情報を書き忘れていましたが↓の通りです
OS: Windows10
ブラウザ: Google Chrome バージョン: 87.0.4280.141（Official Build） （64 ビット）
